[package]
org = "ballerina"
name = "{{MODULE_NAME_CC}}"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/{{REPO_NAME}}"
license = ["Apache-2.0"]
distribution = "{{BAL_VERSION}}"
