#!/usr/bin/env python3
# Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

"""
batch_pr_docs.py

Creates a single pull request from a shared batch branch that already has
multiple connector docs committed to it by batch_commit_docs.py.

Reads the git log of the branch to discover which connectors were committed
and builds a combined PR body listing all of them.

Usage:
    python python/batch_pr_docs.py --branch docs/batch-april-2026

Required:
    --branch BRANCH     The batch branch to open a PR from

Optional:
    --docs-repo PATH        Path to local docs-integrator fork (default: from .env)
    --fork OWNER/REPO       Fork slug (default: DOCS_INTEGRATOR_FORK env var)
    --upstream OWNER/REPO   Upstream repo to target (default: wso2/docs-integrator)
    --base-branch BRANCH    Target branch for the PR (default: main)
    --dry-run               Print planned actions without making any changes
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

sys.path.insert(0, str(Path(__file__).parent))
from publish_docs import (
    DEFAULT_BASE_BRANCH,
    DEFAULT_DOCS_REPO,
    DEFAULT_UPSTREAM,
    create_pr,
    dry,
    fail,
    info,
    infer_fork,
    run,
    validate_docs_repo,
    warn,
)
from pr_preview import checkout_branch


# ── Helpers ───────────────────────────────────────────────────────────────────

def read_connectors_from_branch(docs_repo: Path, base_branch: str) -> list[str]:
    """
    Parse the git log of the current branch since the most recent merge commit
    (i.e. since the last PR from this branch was merged back in) and return the
    list of connector names found in commit messages of the form
    "docs: add {ConnectorName} connector example guide".

    If no merge commit is found on HEAD, falls back to commits since
    origin/{base_branch}.
    """
    last_merge = ""
    try:
        last_merge = run(
            ["git", "log", "--merges", "-n", "1", "--pretty=format:%H", "HEAD"],
            cwd=docs_repo,
        ).strip()
    except subprocess.CalledProcessError:
        pass

    if last_merge:
        info(f"Reading connectors committed since last merge commit {last_merge[:8]}")
        log_range = f"{last_merge}..HEAD"
    else:
        info(f"No merge commit found on branch; using origin/{base_branch}..HEAD")
        log_range = f"origin/{base_branch}..HEAD"

    try:
        log = run(
            ["git", "log", log_range, "--pretty=format:%s"],
            cwd=docs_repo,
        )
    except subprocess.CalledProcessError:
        warn(f"Could not read git log for {log_range}. Trying HEAD~20...")
        log = run(["git", "log", "HEAD~20..HEAD", "--pretty=format:%s"], cwd=docs_repo)

    connectors: list[str] = []
    for subject in log.splitlines():
        m = re.match(r"docs: add (.+) connector example guide", subject, re.IGNORECASE)
        if m:
            connectors.append(m.group(1))

    if not connectors:
        warn(
            "No connector commit messages found in branch log.\n"
            "Expected format: 'docs: add <ConnectorName> connector example guide'"
        )
    return connectors


def build_batch_pr_body(
    connector_names: list[str],
    branch: str,
    base_branch: str,
    upstream: str,
) -> str:
    """Build a PR description that lists all connectors included in the batch."""
    if connector_names:
        connector_list = "\n".join(f"- {name}" for name in connector_names)
        connector_summary = f"the following {len(connector_names)} connector(s)"
    else:
        connector_list = "- (could not detect connector names from git log)"
        connector_summary = "multiple connectors"

    return f"""\
## Purpose

Adds step-by-step example guides for {connector_summary}:

{connector_list}

Each guide covers connection setup and the primary operation with embedded screenshots.

## Goals

- Provide a complete low-code canvas walkthrough for each connector
- Include annotated screenshots at each key configuration step

## Approach

Content generated by the connector-docs-automations pipeline and committed to
branch `{branch}` via `batch_commit_docs.py`.

## Connectors included

{connector_list}

## Release note

Added connector example guides for: {", ".join(connector_names) if connector_names else "multiple connectors"}.

## Security checks

- Followed secure coding standards: N/A (documentation only)
- Ran FindSecurityBugs plugin: N/A (documentation only)
"""


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create a single PR from a batch branch that has multiple connector "
            "docs committed to it by batch_commit_docs.py."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python python/batch_pr_docs.py --branch docs/batch-april-2026\n"
            "  python python/batch_pr_docs.py --branch docs/batch-april-2026 --dry-run\n"
        ),
    )
    parser.add_argument(
        "--branch",
        required=True,
        metavar="BRANCH",
        help="Batch branch to open a PR from (e.g. docs/batch-april-2026)",
    )
    parser.add_argument(
        "--docs-repo",
        default=str(DEFAULT_DOCS_REPO),
        metavar="PATH",
        help=f"Path to local clone of the docs-integrator fork (default: {DEFAULT_DOCS_REPO})",
    )
    parser.add_argument(
        "--fork",
        default=os.environ.get("DOCS_INTEGRATOR_FORK"),
        metavar="OWNER/REPO",
        help="Fork repo slug (default: DOCS_INTEGRATOR_FORK env var or inferred from git remote 'origin')",
    )
    parser.add_argument(
        "--upstream",
        default=DEFAULT_UPSTREAM,
        metavar="OWNER/REPO",
        help=f"Upstream repo to target with the PR (default: {DEFAULT_UPSTREAM})",
    )
    parser.add_argument(
        "--base-branch",
        default=DEFAULT_BASE_BRANCH,
        metavar="BRANCH",
        help=f"Target branch in the upstream repo (default: {DEFAULT_BASE_BRANCH})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without making any changes",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    docs_repo = Path(args.docs_repo).resolve()

    if args.dry_run:
        print("=" * 79)
        print("DRY RUN — no changes will be made")
        print("=" * 79)

    # ── 1. Validate docs repo and resolve fork ─────────────────────────────────
    validate_docs_repo(docs_repo)
    fork = args.fork or infer_fork(docs_repo)
    info(f"Fork: {fork}  |  Upstream: {args.upstream}  |  Base branch: {args.base_branch}")

    # ── 2. Check out the batch branch ─────────────────────────────────────────
    checkout_branch(docs_repo, args.branch, args.dry_run)

    # ── 3. Discover connectors from git log ────────────────────────────────────
    connector_names: list[str] = []
    if not args.dry_run:
        connector_names = read_connectors_from_branch(docs_repo, args.base_branch)
        if connector_names:
            info(f"Found {len(connector_names)} connector(s) in branch log:")
            for name in connector_names:
                info(f"  • {name}")
        else:
            warn("Proceeding with PR creation but connector list is empty.")
    else:
        dry(f"Read git log {args.branch} since origin/{args.base_branch} to find connector names")

    # ── 4. Build PR body ───────────────────────────────────────────────────────
    pr_body = build_batch_pr_body(
        connector_names, args.branch, args.base_branch, args.upstream
    )

    # ── 5. Create PR ───────────────────────────────────────────────────────────
    pr_title = f"docs: adding docs from {args.branch}"

    fork_owner = fork.split("/")[0]
    head = f"{fork_owner}:{args.branch}"

    if args.dry_run:
        dry(f"gh pr create --repo {args.upstream} --head {head} --base {args.base_branch}")
        dry(f"  Title: {pr_title}")
        print()
        print("=" * 79)
        print("Dry run complete. Remove --dry-run to execute.")
        print("=" * 79)
        return

    info(f"Creating PR: {args.upstream} ← {head}")
    try:
        import subprocess as sp
        result = sp.run(
            [
                "gh", "pr", "create",
                "--repo", args.upstream,
                "--head", head,
                "--base", args.base_branch,
                "--title", pr_title,
                "--body", pr_body,
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        pr_url = result.stdout.strip()
    except sp.CalledProcessError as e:
        fail(f"Failed to create PR:\n{e.stderr.strip()}")

    print()
    print("=" * 79)
    print(f"Done!  PR: {pr_url}")
    print("=" * 79)


if __name__ == "__main__":
    main()
