# Build connector `types.bal` from parsed API spec declarations.
#
# + parsedSpec - Parsed API spec containing type declarations and method signatures. Used to extract the header and type definitions for the `types.bal` file.
# + return - Generated Ballerina source code for the connector types, primarily consisting of the header and type definitions extracted from the API spec.
public function buildTypesBal(ParsedApiSpec parsedSpec) returns string {
    string header = "// Auto-generated Connector Types\n" +
                    "// Generated by: Connector Automator\n\n";
    return header + parsedSpec.headerAndTypes + "\n";
}
