[package]
org = "ballerinax"
name = "{{MODULE_NAME_CC}}"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Type/Connector"] # TODO: Add keywords, e.g. "Vendor/<vendor>", "Area/<area>"
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/{{REPO_NAME}}"
license = ["Apache-2.0"]
distribution = "{{BAL_VERSION}}"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "{{MODULE_NAME_CC}}-native"
version = "@toml.version@"
path = "../native/build/libs/{{MODULE_NAME_CC}}-native-@project.version@.jar"
