#!/usr/bin/env python3
"""Persist stable OpenAPI operationId decisions in ai-mappings.json.

Usage:
  operation_id_mappings.py prepare <aligned-spec.json> <ai-mappings.json> <candidate.json>
  operation_id_mappings.py apply <aligned-spec.json> <candidate.json> <decisions.json> <ai-mappings.json>
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

HTTP_METHODS = ("get", "post", "put", "delete", "patch", "head", "options", "trace")
WARNING = "AUTO-GENERATED FILE. DO NOT MODIFY. This file is generated by the Ballerina connector tool."


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key '{key}'")
        result[key] = value
    return result


def read_json(path: str, default: Any = None, reject_duplicates: bool = False) -> Any:
    if not os.path.exists(path):
        return default
    try:
        with open(path, encoding="utf-8") as file:
            return json.load(file, object_pairs_hook=reject_duplicate_keys if reject_duplicates else None)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        fail(f"could not read JSON file {path}: {exc}")


def ordered_document(document: dict[str, Any]) -> dict[str, Any]:
    result = {"_warning": WARNING}
    result.update({key: value for key, value in document.items() if key != "_warning"})
    return result


def atomic_write_json(path: str, value: Any) -> None:
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".connector-operation-ids-", suffix=".json", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            json.dump(value, file, indent=2, ensure_ascii=False)
            file.write("\n")
            file.flush()
            os.fsync(file.fileno())
        os.replace(temporary, path)
    except OSError as exc:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        fail(f"could not atomically write {path}: {exc}")


def operations(spec: dict[str, Any]) -> dict[tuple[str, str], dict[str, Any]]:
    result: dict[tuple[str, str], dict[str, Any]] = {}
    paths = spec.get("paths")
    if not isinstance(paths, dict):
        fail("aligned specification has no paths mapping")
    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if isinstance(operation, dict):
                result[(path, method)] = operation
    return result


def load_document(path: str) -> dict[str, Any]:
    document = read_json(path, {})
    if not isinstance(document, dict):
        fail("ai-mappings.json must contain a JSON object")
    stored = document.get("operationIds", {})
    if not isinstance(stored, dict):
        fail("ai-mappings.json operationIds must be a JSON object")
    for path_key, methods in stored.items():
        if not isinstance(path_key, str) or not isinstance(methods, dict):
            fail("ai-mappings.json operationIds must map paths to method objects")
        for method, operation_id in methods.items():
            if method not in HTTP_METHODS:
                fail(f"unsupported operationId method '{method}' for '{path_key}'")
            if not isinstance(operation_id, str) or not operation_id.strip():
                fail(f"operationId for '{method} {path_key}' must be a non-empty string")
    return document


def sorted_mappings(flat: dict[tuple[str, str], str]) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for path, method in sorted(flat, key=lambda item: (item[0], HTTP_METHODS.index(item[1]))):
        result.setdefault(path, {})[method] = flat[(path, method)]
    return result


def operation_metadata(path: str, method: str, operation: dict[str, Any]) -> dict[str, Any]:
    parameters = []
    for parameter in operation.get("parameters") or []:
        if isinstance(parameter, dict):
            parameters.append({
                "name": parameter.get("name", ""),
                "in": parameter.get("in", ""),
                "required": bool(parameter.get("required", False)),
            })
    return {
        "path": path,
        "method": method,
        "current_operation_id": operation.get("operationId", ""),
        "summary": (operation.get("summary") or "")[:200],
        "description": (operation.get("description") or "")[:300],
        "tags": operation.get("tags") or [],
        "parameters": parameters,
    }


def prepare(spec_path: str, mappings_path: str, candidate_path: str) -> None:
    spec = read_json(spec_path)
    if not isinstance(spec, dict):
        fail("aligned specification must contain a JSON object")
    document = load_document(mappings_path)
    current = operations(spec)
    stored = document.get("operationIds", {})
    reusable: dict[tuple[str, str], str] = {}
    pruned: list[str] = []
    owners: dict[str, str] = {}

    for path, methods in stored.items():
        for method, raw_id in methods.items():
            location = (path, method)
            if location not in current:
                pruned.append(f"{method} {path}")
                continue
            operation_id = raw_id.strip()
            owner = owners.get(operation_id)
            location_name = f"{method} {path}"
            if owner is not None:
                fail(f"duplicate persisted operationId '{operation_id}' for '{owner}' and '{location_name}'")
            owners[operation_id] = location_name
            reusable[location] = operation_id
            current[location]["operationId"] = operation_id

    unseen = [
        operation_metadata(path, method, current[(path, method)])
        for path, method in sorted(current, key=lambda item: (item[0], HTTP_METHODS.index(item[1])))
        if (path, method) not in reusable
    ]
    candidate = dict(document)
    candidate["operationIds"] = sorted_mappings(reusable)
    candidate["_operationIdState"] = {
        "reused_count": len(reusable),
        "pruned_count": len(pruned),
    }
    atomic_write_json(candidate_path, ordered_document(candidate))
    if reusable:
        atomic_write_json(spec_path, spec)
    print(json.dumps({
        "reused_count": len(reusable),
        "pruned_count": len(pruned),
        "pruned_operations": sorted(pruned),
        "unseen_operations": unseen,
        "reserved_operation_ids": sorted(owners),
        "candidate_path": str(Path(candidate_path)),
    }))


def parse_decisions(value: Any) -> dict[tuple[str, str], str]:
    if not isinstance(value, dict):
        fail("operationId decisions must be a JSON object")
    result: dict[tuple[str, str], str] = {}
    for path, methods in value.items():
        if not isinstance(path, str) or not isinstance(methods, dict):
            fail("operationId decisions must map paths to method objects")
        for method, operation_id in methods.items():
            if method not in HTTP_METHODS:
                fail(f"unsupported operationId decision method '{method}' for '{path}'")
            if not isinstance(operation_id, str) or not operation_id.strip():
                fail(f"operationId decision for '{method} {path}' must be a non-empty string")
            result[(path, method)] = operation_id.strip()
    return result


def apply(spec_path: str, candidate_path: str, decisions_path: str, output_path: str) -> None:
    spec = read_json(spec_path)
    if not isinstance(spec, dict):
        fail("aligned specification must contain a JSON object")
    candidate = load_document(candidate_path)
    state = candidate.pop("_operationIdState", {})
    decisions = parse_decisions(read_json(decisions_path, reject_duplicates=True))
    current = operations(spec)
    existing_nested = candidate.get("operationIds", {})
    existing = {
        (path, method): operation_id
        for path, methods in existing_nested.items()
        for method, operation_id in methods.items()
        if (path, method) in current
    }
    unseen = set(current) - set(existing)
    unexpected = sorted(set(decisions) - unseen)
    if unexpected:
        fail("operationId decisions contain unexpected operations: " +
             ", ".join(f"{method} {path}" for path, method in unexpected))

    reserved = set(existing.values())
    for location in unseen - set(decisions):
        operation_id = current[location].get("operationId")
        if isinstance(operation_id, str) and operation_id.strip():
            reserved.add(operation_id.strip())
    final_decisions: dict[tuple[str, str], str] = {}
    changed = 0
    for location in sorted(decisions, key=lambda item: (item[0], HTTP_METHODS.index(item[1]))):
        requested = decisions[location]
        final_id = requested
        suffix = 1
        while final_id in reserved:
            final_id = f"{requested}{suffix}"
            suffix += 1
        operation = current[location]
        if operation.get("operationId") != final_id:
            changed += 1
        operation["operationId"] = final_id
        final_decisions[location] = final_id
        reserved.add(final_id)

    merged = {**existing, **final_decisions}
    candidate["operationIds"] = sorted_mappings(merged)
    atomic_write_json(spec_path, spec)
    atomic_write_json(output_path, ordered_document(candidate))
    print(json.dumps({
        "applied_count": len(final_decisions),
        "changed_count": changed,
        "pending_count": len(unseen - set(decisions)),
        "reused_count": state.get("reused_count", len(existing)) if isinstance(state, dict) else len(existing),
        "pruned_count": state.get("pruned_count", 0) if isinstance(state, dict) else 0,
        "reserved_operation_ids": sorted(reserved),
    }))


def usage() -> None:
    print(f"Usage: {sys.argv[0]} prepare <aligned-spec.json> <ai-mappings.json> <candidate.json>", file=sys.stderr)
    print(f"       {sys.argv[0]} apply <aligned-spec.json> <candidate.json> <decisions.json> <ai-mappings.json>", file=sys.stderr)
    raise SystemExit(2)


if __name__ == "__main__":
    if len(sys.argv) == 5 and sys.argv[1] == "prepare":
        prepare(*sys.argv[2:])
    elif len(sys.argv) == 6 and sys.argv[1] == "apply":
        apply(*sys.argv[2:])
    else:
        usage()
