org.gradle.caching=true
group=io.ballerina.lib
version={{MODULE_VERSION}}-SNAPSHOT

ballerinaLangVersion={{BAL_VERSION}}

releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0
spotbugsPluginVersion=6.5.1
downloadPluginVersion=5.4.0
checkstylePluginVersion=10.12.1
# {{#COMPILER_PLUGIN}}
jacocoVersion=0.8.14
testngVersion=7.6.1
# {{/COMPILER_PLUGIN}}
