name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Select the area this issue relates to
      options:
        - Area/AI
        - Area/AIAgent
        - Area/AzureWebsubHub
        - Area/BallerinaToOpenapi
        - Area/Build
        - Area/CompilerPlugin
        - Area/Connector
        - Area/Docs
        - Area/EventIntegration
        - Area/FileIntegration
        - Area/GraalVM
        - Area/GradlePlugin
        - Area/Healthcare
        - Area/KafkaHub
        - Area/LangLibrary
        - Area/Library
        - Area/Observerbility
        - Area/OpenapiToBallerina
        - Area/Security
        - Area/StaticCode
        - Area/Tooling
        - Area/Workflow
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: false
