name: Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  call_workflow:
    name: Run Security Scan Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/security-scan-template.yml@main
    secrets: inherit
