name: Daily Build (Connector)

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      additional-build-flags:
        required: false
        type: string
        default: ""
      additional-test-flags:
        required: false
        type: string
        default: ""

jobs:
  ubuntu-build:
    name: Build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-build
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build -x test ${{ inputs.additional-build-flags }} -PbuildUsingDocker=nightly

      - name: Test the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew test ${{ inputs.additional-test-flags }} -PbuildUsingDocker=nightly

      # Send notification when build fails
      - name: Notify failure
        if: ${{ failure() }}
        run: |
          curl -X POST \
          'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data "{
            \"event_type\": \"notify-build-failure\",
            \"client_payload\": {
              \"repoName\": \"${{ inputs.repo-name }}\"
            }
          }"
