name: Regenerate OpenAPI Connectors Template

on:
  workflow_call:
    inputs:
      openapi-url:
        description: "URL of the OpenAPI JSON"
        required: false
        type: string
      flatten-openapi:
        description: "Enable OpenAPI Flattening"
        required: false
        type: boolean
        default: true
      additional-flatten-flags:
        description: "Additional flags for OpenAPI Flattening"
        required: false
        type: string
        default: ""
      align-openapi:
        description: "Enable OpenAPI Alignment"
        required: false
        type: boolean
        default: true
      additional-align-flags:
        description: "Additional flags for OpenAPI Alignment"
        required: false
        type: string
        default: ""
      additional-generation-flags:
        description: "Additional flags for OpenAPI Generation"
        required: false
        type: string
        default: ""
      generation-path:
        description: "Generation path for the OpenAPI Connector"
        required: false
        type: string
        default: "ballerina"
      distribution-zip:
        description: "Distribution of the Ballerina version to be used"
        required: false
        type: string
        default: ""
      auto-merge:
        description: "Enable auto-merge of the PR"
        required: false
        type: boolean
        default: true
      ballerina-version:
        description: "Ballerina Language Version"
        required: false
        type: string
        default: ""

jobs:
  build:
    name: Regenerate openapi-connector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}

      - name: Set Ballerina Version
        if: ${{ inputs.ballerina-version }}
        run: |
          FILE="gradle.properties"
          sed -i "s/^ballerinaLangVersion=.*/ballerinaLangVersion=${{ inputs.ballerina-version }}/" "$FILE"

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then
              BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"
          echo "BALLERINA_CMD=bal" >> $GITHUB_ENV

      - name: Set Up Ballerina
        if: ${{ inputs.distribution-zip == '' }}
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Remove Existing Client Files
        working-directory: ${{ inputs.generation-path }}
        run: |
          rm -f client.bal utils.bal types.bal

      - name: Get Ballerina Distribution
        if: ${{ inputs.distribution-zip }}
        run: |
          pwd
          echo "Downloading Ballerina distribution from provided URL..."
          wget -q --no-check-certificate -O ballerina.zip "${{ inputs.distribution-zip }}"
          unzip -o -q ballerina.zip -d temp_folder/
          cp -r temp_folder/ballerina-*/. ballerina-dist/
          rm -r temp_folder/ ballerina.zip
          echo "BALLERINA_CMD=${PWD}/ballerina-dist/bin/bal" >> $GITHUB_ENV

      - name: Download spec file
        if: ${{ inputs.openapi-url }}
        working-directory: docs/spec
        run: |
          echo "Downloading openapi spec from provided URL..."
          if [[ "${{ inputs.openapi-url }}" == *.json ]]; then
            rm -f openapi.json
            wget -O openapi.json "${{ inputs.openapi-url }}"
          elif [[ "${{ inputs.openapi-url }}" == *.yaml || "${{ inputs.openapi-url }}" == *.yml ]]; then
            rm -f openapi.yaml openapi.yml
            wget -O openapi.yaml "${{ inputs.openapi-url }}"
          else
            echo "Unsupported file extension: ${{ inputs.openapi-url }}"
            exit 1
          fi

      - name: Read File Extension
        working-directory: docs/spec
        run: |
          file=$(echo openapi.*)
          ext="${file##*.}"
          echo "EXTENSION=$ext" >> "$GITHUB_ENV"

      - name: Checkout or Create Branch
        run: |
          if git show-ref --verify --quiet refs/heads/regenerate-connector; then
            git checkout regenerate-connector
          else
            git checkout -b regenerate-connector
          fi

      - name: Flatten OpenAPI Specification
        if: ${{ inputs.flatten-openapi }}
        working-directory: docs/spec
        run: |
          echo "Flattening OpenAPI Specification..."
          ${{ env.BALLERINA_CMD }} openapi flatten -i openapi.${{ env.EXTENSION}} ${{ inputs.additional-flatten-flags }}
          mv flattened_openapi.${{ env.EXTENSION}} openapi.${{ env.EXTENSION}}

      - name: Align OpenAPI Specification
        working-directory: docs/spec
        if: ${{ inputs.align-openapi }}
        run: |
          echo "Aligning OpenAPI Specification..."
          ${{ env.BALLERINA_CMD }} openapi align -i openapi.${{ env.EXTENSION}} ${{ inputs.additional-align-flags }}
          mv aligned_ballerina_openapi.${{ env.EXTENSION}} openapi.${{ env.EXTENSION}}

      - name: Generate Ballerina Code
        working-directory: docs/spec
        run: |
          echo "Generating Ballerina code from OpenAPI Specification..."
          ${{ env.BALLERINA_CMD }} openapi -i openapi.${{ env.EXTENSION}} -o ../../${{ inputs.generation-path }}/  --mode client --license ../license.txt ${{ inputs.additional-generation-flags }}

      - name: Configure Git Identity
        run: |
          git config user.name "ballerina-bot"
          git config user.email "ballerina-bot@ballerina.org"

      - name: Remove uncommitted files
        run: |
          rm -f -r ballerina-dist/

      - name: Commit Files
        id: commitFiles
        run: |
          changed=false
          # First commit: OpenAPI spec changes
          git add docs/spec/
          if ! git diff --cached --quiet; then
            git commit -m "[AUTOMATED] Update OpenAPI spec"
            changed=true
          fi

          # Second commit: all other changes
          git add .
          git reset docs/spec/
          if ! git diff --cached --quiet; then
            git commit -m "[AUTOMATED] Client Regeneration"
            changed=true
          fi

          # Set output if anything changed
          if [ "$changed" = true ]; then
            echo "hasChanged=true" >> $GITHUB_OUTPUT
          else
            echo "hasChanged=false" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          fi

      - name: Push Results
        if: ${{ steps.commitFiles.outputs.hasChanged == 'true' }}
        run: git push origin regenerate-connector
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}

      - name: Create Pull Request
        id: createPR
        if: ${{ steps.commitFiles.outputs.hasChanged == 'true' }}
        run: |
          prUrl=$(gh pr create \
            --title "[Automated] Regenerate OpenAPI Connector" \
            --body $'Automated regenerate of the OpenAPI-based Ballerina connector.\n\nFollow the steps to view the OpenAPI changes:\n1. Copy the following URL:\n```\nhttps://github.com/ballerina-platform/${{ github.event.repository.name }}/blob/regenerate-connector/docs/spec/openapi.${{ env.EXTENSION }}\n```\n\n2. Visit [pb33f OpenAPI Changes](https://pb33f.io/openapi-changes/demo/) and provide the above URL as the GitHub URL.' \
            --base ${{ github.ref }} \
            --head regenerate-connector)
          echo "prUrl=$prUrl" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}

      - name: Approve PR
        if: ${{ steps.commitFiles.outputs.hasChanged == 'true' }}
        run: |
          sleep 5
          gh pr review --approve ${{ steps.createPR.outputs.prUrl }}
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_REVIEWER_BOT_TOKEN }}

      - name: Merge PR
        if: ${{ steps.commitFiles.outputs.hasChanged == 'true' && inputs.auto-merge == true }}
        run: |
          checkComplete="0"
          while [ "$checkComplete" != "1" ]; do
            sleep 20

            allChecks=$(gh pr status --json statusCheckRollup --jq '.currentBranch.statusCheckRollup')
            failedCount=$(echo "$allChecks" | jq '[.[] | select(.conclusion == "FAILURE" or .conclusion == "CANCELLED")] | length')
            incompleteCount=$(echo "$allChecks" | jq '[.[] | select(.conclusion != "SUCCESS" and .conclusion != "SKIPPED" and .conclusion != "FAILURE" and .conclusion != "CANCELLED")] | length')

            if [[ "$failedCount" -gt 0 ]]; then
              echo "Some status checks failed or were cancelled."
              exit 1
            fi

            if [[ "$incompleteCount" -eq 0 ]]; then
              checkComplete="1"
              echo "All required checks have passed."
            else
              echo "Waiting for checks to complete... ($incompleteCount remaining)"
            fi
          done
          sleep 20
          gh pr merge --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
